### ISSUE TITLE
OneTime = false does nothing

### ISSUE THREAD

**Issue by gabwiel** [BookHorseSoftware/SteamGroupRewardsFramework#10]
I can't get the reward multiple times to test, it just says that I'm in the group in the server's console (debug mode enabled) but no rewards

**Comment by BytewaveMLP** [comment]
I suppose I should document it better, and add an option for a recurring reward.

`OneTime` is meant to only occur once, ever. If you leave the group and rejoin, you won't receive the `OneTime` rewards again. All rewards are only presented when you join the group, and not on every spawn, at this time.

I'll look into adding a `Recurring`  option for rewards, which should allow you to receive the reward every time you connect to the server.

**Comment by BytewaveMLP** [comment]
Hopefully that change will work. I don't have easy access to a test server at the moment, so do you mind testing them for me?

**Comment by gabwiel** [comment]
Alright it's working :) Thanks, but I think you should add a delay before launching the callback because some addons like Pointshop aren't loaded yet

**Comment by BytewaveMLP** [comment]
Er... everything *should* run on the server, which means everything should be initialized a few seconds or so after the map is loaded. If they join right as the server starts, maybe that's an issue, but I can't really rely on ULib's hook priority system here (which would be a huge help with fixing this) without relying on ULib itself.

I'll look into it, but I haven't worked on GMod addons in quite a while, so a lot of my knowledge is flaky.
