### ISSUE TITLE
Group membership no longer reported for private profiles

### ISSUE THREAD

**Issue by BytewaveMLP** [BookHorseSoftware/SteamGroupRewardsFramework#3]
Since adopting the official Steam API, private profiles are no longer reported as being members of the Steam group. The official Steam API (perhaps rightfully so) doesn't report details on private user profiles, but some people may wish to keep their profiles private. The XML method, while more annoying, works with private profiles as it queries the **group**, not the **profile**.

CC @antigravities

**Comment by BytewaveMLP** [comment]
Possible Lua-only XML parsing solutions listed [here](http://lua-users.org/wiki/LuaXml).

**Comment by antigravities** [comment]
K, so we should use the JSON by default and if [something happens](https://fud.community.services.support.microsoft.com/Fud/FileDownloadHandler.ashx?fid=f11faae2-c44a-4b98-8cba-3198ddab7cac) we should fall back to the XML. We can easily check this because a request for a private profile returns:
````
{
	"response": {
		"success": false,
		"error": "Private profile"
	}
}
````

**Comment by BytewaveMLP** [comment]
Preliminary fix committed. Could use a little bit more work; maybe I should've issued a PR. But my tests show everything works.

Hopefully I didn't commit any of my debugging stuff. :)

**Comment by BytewaveMLP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use fallback XML method for checking Steam group membership when profile is private](https://trello.com/c/VSTnO2Za/3-use-fallback-xml-method-for-checking-steam-group-membership-when-profile-is-private)

**Comment by BytewaveMLP** [comment]
I'm leaving this issue open as it still needs some work. While I know it's very much an edge case, at least one issue I know of is that **any** text field [SLAXML](https://github.com/Phrogz/SLAXML) finds that equals a user's SteamID64 will treat that user as in the group, regardless if it's a `<steamID64>` tag or not. I would filter based on tag if I could figure out how, but SLAXML's weird callback-parsing syntax makes that difficult.

Another issue I see is that we don't really handle invalid responses from the XML API, and if the Steam API request fails on our end we don't fall back properly. I would write a function, but again, the `http` library's use of callbacks makes things difficult.

**Comment by BytewaveMLP** [comment]
```
4:02 PM - Adam: also [SGRF]: TRACE: {
"response": {
"success": false,
"error": "Private profile"
}
}
[SGRF]: DEBUG: Steam API check failed for player Echoerr (STEAM_0:1:52758241) - attempting fallback XML method...
[SGRF]: DEBUG: Player Echoerr (STEAM_0:1:52758241) is not in group (XML API).
4:02 PM - Byte: is he in the group?
4:02 PM - Adam: yes
4:02 PM - Byte: wtf
4:02 PM - Byte: it
4:02 PM - Byte: worked in local testing
4:02 PM - Byte: inb4...
4:03 PM - Adam: only broke for private profiles
4:03 PM - Byte: it worked earlier dammit
4:03 PM - Byte: what is the group ID for hh?
4:04 PM - Byte: http://steamcommunity.com/gid/YYYYYYY/memberslistxml/?xml=1

put it in YYYYYY and ul42lpaste the results
4:05 PM - Adam: 28484217
4:05 PM - Adam: k
4:05 PM - Byte: thz
4:05 PM - Byte: thx*
4:06 PM - Byte: what is echoerr's sid64?
4:07 PM - Adam: 76561198065782211
4:07 PM - Byte: hmm...
```

**Comment by BytewaveMLP** [comment]
As far as I can tell, this is done. Yay!
