### ISSUE TITLE
Not working for the group creator

### ISSUE THREAD

**Issue by gabwiel** [BookHorseSoftware/SteamGroupRewardsFramework#8]
I set up everything correctly, but it still says that I'm not in the group :/

**Comment by gabwiel** [comment]
Apparently this is not working at all :(..
Here's my config file :

`--- The group ID to check
-- This is your group's ID. You can find this on your group's profile edit page, after the "ID:"
-- label.
SGRF.Config.SteamGroup = '103582791462965920'

--- Your Steam Web API key
-- You can get this at https://steamcommunity.com/dev/apikey.
SGRF.Config.SteamAPIKey = '96785B3C7E9E4CC9E43DDCDBBD5****A'

--- Should DEBUG-level log messages be printed?
-- You should really only set this to true if asked to by the developers. This will cause a lot of
-- console spam.
SGRF.Config.LogDebugMessages = true`

**Comment by BytewaveMLP** [comment]
You have debug messages enabled, as far as I can see. Do you know how to access the server console, and do you think you can retrieve the logged debug messages for me there?

**Comment by gabwiel** [comment]
[SGRF]: TRACE: {"response":{"success":true,"groups":[{"gid":"1850"},{"gid":"3402
923"},{"gid":"4264294"},{"gid":"4771848"},{"gid":"5151157"},{"gid":"6869120"},{"
gid":"8797323"},{"gid":"27271321"},{"gid":"28981418"},{"gid":"32332269"},{"gid":
"33072940"},{"gid":"33444512"}]}}
[SGRF]: DEBUG: Player <Gabwiel> (STEAM_0:1:73267136) is not in group.

**Comment by BytewaveMLP** [comment]
It looks like you're using the wrong group ID. It still resolves to your Steam group, but the actual group ID that the Steam API will give back to me is `33444512`. As noted in the [Configuration](https://github.com/BookHorseSoftware/SteamGroupRewardsFramework#configuration) section of the README, this group ID can be found under the "edit profile" section of the Steam group, **not** under the `memberslistxml` endpoint.

**Comment by BytewaveMLP** [comment]
Whoops, looks like I must've used the wrong function name when I added that helper function, like... a year or two ago. Guess it's just gone unreported til now.

Fixed in 447fd78.
